"""
Automated Test Suite for Advanced PCB Inspection & Metrology Features
Tests CAD Centroid Parser, Metrology Engine, Substrate Leveler, and CFX Dispatcher.
"""

import pytest
import numpy as np
import cv2
from server.pipeline.cad_parser import CADParser
from server.pipeline.metrology_engine import MetrologyEngine
from server.pipeline.substrate_leveler import SubstrateLeveler
from server.pipeline.cfx_dispatcher import CFXDispatcher

def test_cad_parser():
    parser = CADParser(pcb_width_mm=100.0, pcb_height_mm=80.0)
    sample_csv = """# SMT Centroid File Generated by Altium
Designator, Package, Mid X, Mid Y, Rotation, Value
U1, QFP-64, 50.0, 40.0, 0.0, STM32F4
C1, 0402, 20.0, 15.0, 90.0, 100nF
R1, 0603, 75.0, 60.0, 0.0, 10k
CONN1, USB-C, 10.0, 40.0, 270.0, TYPE-C
"""
    components = parser.parse_centroid_csv(sample_csv, image_shape=(800, 1000))
    assert len(components) == 4
    
    u1 = next(c for c in components if c["id"] == "U1")
    assert u1["type"] == "IC"
    assert len(u1["bbox_xywh"]) == 4
    assert u1["weight"] == 5.0

def test_substrate_leveler():
    leveler = SubstrateLeveler(sample_grid_step=8)
    
    # Create a 200x200 synthetic depth map with a known linear tilt: Z = 0.002*X + 0.001*Y + 0.1
    img_h, img_w = 200, 200
    grid_x, grid_y = np.meshgrid(np.arange(img_w), np.arange(img_h))
    tilted_depth = (0.002 * grid_x + 0.001 * grid_y + 0.1).astype(np.float32)

    components = [
        {"id": "U1", "bbox_xywh": [80, 80, 40, 40]}
    ]

    leveled, plane_depth, stats = leveler.level_depth_map(tilted_depth, components)
    
    assert leveled.shape == tilted_depth.shape
    # Non-component substrate regions should be close to 0.0 after plane subtraction
    substrate_sample = leveled[10:30, 10:30]
    assert np.mean(substrate_sample) < 0.05
    assert "board_roll_deg" in stats

def test_metrology_engine():
    engine = MetrologyEngine(px_to_mm_scale=0.05)
    
    # Create a synthetic reference chip (centered square)
    ref_roi = np.zeros((60, 60, 3), dtype=np.uint8)
    cv2.rectangle(ref_roi, (15, 15), (45, 45), (200, 200, 200), -1)

    # Create a test chip shifted by 5 pixels in X and 3 pixels in Y
    test_roi = np.zeros((60, 60, 3), dtype=np.uint8)
    cv2.rectangle(test_roi, (20, 18), (50, 48), (200, 200, 200), -1)

    comp_info = {
        "id": "U1",
        "bbox_xywh": [100, 100, 60, 60],
        "type": "IC"
    }

    res = engine.inspect_component_metrology(test_roi, ref_roi, comp_info)
    assert res["component_id"] == "U1"
    assert abs(res["delta_x_px"] - 5.0) < 1.5
    assert abs(res["delta_y_px"] - 3.0) < 1.5
    assert res["delta_x_mm"] > 0
    assert "ipc_class_verdict" in res

def test_cfx_dispatcher():
    dispatcher = CFXDispatcher(line_id="SMT-LINE-01", station_id="AOI-TEST-01")
    
    hi_results = {
        "verdict": "REWORK",
        "health_index": 0.88,
        "total_components": 12,
        "components": [
            {
                "id": "C3",
                "status": "TOMBSTONE",
                "presence_score": 0.90,
                "height_penalty": 0.45
            }
        ]
    }
    metrology_results = [
        {
            "component_id": "C3",
            "delta_x_mm": 0.15,
            "delta_y_mm": 0.05,
            "rotation_deg": 12.5,
            "max_overhang_pct": 35.0,
            "ipc_class_verdict": "PROCESS_INDICATOR"
        }
    ]

    event = dispatcher.generate_inspection_event("BOARD-12345", hi_results, metrology_results, 185.0)
    
    header = event["CFXMessage"]["Header"]
    body = event["CFXMessage"]["Body"]
    
    assert header["MessageType"] == "CFX.Production.AssemblyInspectionCompleted"
    assert body["BoardSerialNumber"] == "BOARD-12345"
    assert body["InspectionResult"] == "REWORK"
    assert len(body["DefectList"]) == 1
    assert body["DefectList"][0]["ComponentDesignator"] == "C3"
